"""
Summarize per-tool edge tables and write a network QC table.

Usage:
    python scripts/03_network_summary_statistics.py

Required input files:
    - data/edges/<collapse_rule>/<threshold>/<tool>.edges.tsv

These edge tables are produced by scripts/02_build_edge_tables.py. The script loops
over both collapse rules, all thresholds, and all three tools, so the corresponding
edge files must exist in the data/edges/ directory tree before running this step.

This script reads the edge tables generated by scripts/02_build_edge_tables.py,
calculates node, edge, component, degree, and alignment-quality statistics for each
tool/threshold/collapse-rule combination, and writes the summary TSV to
data/quality_checks/.
"""
from __future__ import annotations

from pathlib import Path
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]

EDGE_ROOT = PROJECT_ROOT / "data" / "edges"
QC_OUTPUT_DIR = PROJECT_ROOT / "data" / "quality_checks"

COLLAPSE_RULES = [
    "best_bitscore",
    "best_evalue",
]

THRESHOLDS = [
    "raw",
    "evalue_1e-3",
    "evalue_1e-5",
    "evalue_1e-10",
]

TOOLS = [
    "blastp",
    "mmseqs",
    "swipe",
]


class UnionFind:
    size: dict[str, int]
    parent: dict[str, str]
    """Simple union-find data structure for connected components"""

    def __init__(self):
        self.parent = {}
        self.size = {}

    def add(self, x: str) -> None:
        """Add a node x to the union-find structure if it doesn't exist"""
        if x not in self.parent:
            self.parent[x] = x
            self.size[x] = 1

    def find(self, x: str) -> str:
        """Find the root of node x in the union-find structure"""
        while self.parent[x] != x:
            self.parent[x] = self.parent[self.parent[x]]
            x = self.parent[x]
        return x

    def union(self, a: str, b: str) -> None:
        """Union two nodes a and b in the union-find structure"""
        self.add(a)
        self.add(b)

        root_a = self.find(a)
        root_b = self.find(b)

        if root_a == root_b:
            return

        if self.size[root_a] < self.size[root_b]:
            root_a, root_b = root_b, root_a

        self.parent[root_b] = root_a
        self.size[root_a] += self.size[root_b]

    def component_sizes(self) -> list[int]:
        """Return a list of sizes of all connected components"""
        roots = {}

        for node in self.parent:
            root = self.find(node)
            roots[root] = roots.get(root, 0) + 1

        return list(roots.values())


def calculate_network_summary(
    edge_file: Path,
    collapse_rule: str,
    threshold: str,
    tool: str,
) -> dict:
    """Calculate summary statistics for a given edge file"""
    print(f"Processing {collapse_rule} | {threshold} | {tool}")

    edges = pd.read_csv(edge_file, sep="\t")

    required_cols = {"source", "target", "pident", "length", "evalue", "bitscore"}
    missing_cols = required_cols - set(edges.columns)

    if missing_cols:
        raise ValueError(f"{edge_file} is missing required columns: {missing_cols}")

    raw_edge_rows = len(edges)

    self_edges = edges[edges["source"] == edges["target"]]
    self_edge_count = len(self_edges)

    if self_edge_count > 0:
        print(f"  Warning: removing {self_edge_count} self-edges from {edge_file}")
        edges = edges[edges["source"] != edges["target"]].copy()

    duplicate_edges = edges.duplicated(subset=["source", "target"]).sum()

    if duplicate_edges > 0:
        print(f"  Warning: {duplicate_edges} duplicate source-target edges detected.")

    n_edges = len(edges)

    all_nodes = pd.concat([edges["source"], edges["target"]], ignore_index=True)
    n_nodes = all_nodes.nunique()

    degree_series = all_nodes.value_counts()

    average_degree = (2 * n_edges / n_nodes) if n_nodes > 0 else 0

    if n_nodes > 1:
        density = (2 * n_edges) / (n_nodes * (n_nodes - 1))
    else:
        density = 0

    uf = UnionFind()

    for source, target in zip(edges["source"], edges["target"]):
        uf.union(source, target)

    component_sizes = uf.component_sizes()

    n_components = len(component_sizes)
    largest_component_size = max(component_sizes) if component_sizes else 0
    largest_component_fraction = (
        largest_component_size / n_nodes if n_nodes > 0 else 0
    )

    perfect_identity_edges = int((edges["pident"] == 100).sum())

    return {
        "collapse_rule": collapse_rule,
        "threshold": threshold,
        "tool": tool,
        "edge_file": str(edge_file.relative_to(PROJECT_ROOT)),
        "raw_edge_rows": raw_edge_rows,
        "self_edges_detected": self_edge_count,
        "duplicate_edges_detected": int(duplicate_edges),
        "nodes_with_at_least_one_edge": n_nodes,
        "edges": n_edges,
        "average_degree": average_degree,
        "density": density,
        "connected_components": n_components,
        "largest_component_size": largest_component_size,
        "largest_component_fraction": largest_component_fraction,
        "min_degree": degree_series.min(),
        "median_degree": degree_series.median(),
        "mean_degree": degree_series.mean(),
        "max_degree": degree_series.max(),
        "perfect_identity_edges": perfect_identity_edges,
        "perfect_identity_edge_fraction": (
            perfect_identity_edges / n_edges if n_edges > 0 else 0
        ),
        "median_pident": edges["pident"].median(),
        "median_alignment_length": edges["length"].median(),
        "median_bitscore": edges["bitscore"].median(),
        "min_evalue": edges["evalue"].min(),
        "max_evalue": edges["evalue"].max(),
    }


def main() -> None:
    QC_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    summary_rows = []

    for collapse_rule in COLLAPSE_RULES:
        for threshold in THRESHOLDS:
            for tool in TOOLS:
                edge_file = EDGE_ROOT / collapse_rule / threshold / f"{tool}.edges.tsv"

                if not edge_file.exists():
                    print(f"Skipping missing file: {edge_file}")
                    continue

                summary_rows.append(
                    calculate_network_summary(
                        edge_file=edge_file,
                        collapse_rule=collapse_rule,
                        threshold=threshold,
                        tool=tool,
                    )
                )

    summary_df = pd.DataFrame(summary_rows)

    output_file = QC_OUTPUT_DIR / "network_summary_statistics.tsv"
    summary_df.to_csv(output_file, sep="\t", index=False)

    print("\nNetwork summary statistics:")
    print(summary_df.to_string(index=False))
    print(f"\nSummary written to: {output_file}")


if __name__ == "__main__":
    main()
