"""
Summarize integrated networks for each threshold and consensus filter.

Usage:
    python scripts/05_integrated_network_summary.py

Required input files:
    - data/edges/integrated/<collapse_rule>/<threshold>/integrated_edges.tsv

This script currently reads the integrated edge tables produced for the
best_bitscore collapse rule and all thresholds, so those files must exist before
running it.

This script reads the integrated edge tables generated by
scripts/04_integrate_tool_support.py, calculates network-level statistics for the
all-edges and consensus-filtered networks, and writes the summary TSV to
data/quality_checks/.
"""
from __future__ import annotations

from pathlib import Path
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]

INTEGRATED_EDGE_ROOT = PROJECT_ROOT / "data" / "edges" / "integrated" / "best_bitscore"
QC_OUTPUT_DIR = PROJECT_ROOT / "data" / "quality_checks"

THRESHOLDS = [
    "raw",
    "evalue_1e-3",
    "evalue_1e-5",
    "evalue_1e-10",
]

USECOLS = [
    "source",
    "target",
    "n_tools",
    "tools",
    "support_pattern",
    "pident_max",
    "align_len_max",
    "evalue_min",
    "bitscore_max",
]


class UnionFind:
    parent: dict[str, str]
    size: dict[str, int]
    """Memory-friendly connected component calculation for large undirected graphs"""

    def __init__(self):
        self.parent = {}
        self.size = {}

    def add(self, x: str) -> None:
        """Add a node x to the union-find structure if it doesn't exist"""
        if x not in self.parent:
            self.parent[x] = x
            self.size[x] = 1

    def find(self, x: str) -> str:
        """Find the root of node x in the union-find structure"""
        while self.parent[x] != x:
            self.parent[x] = self.parent[self.parent[x]]
            x = self.parent[x]
        return x

    def union(self, a: str, b: str) -> None:
        """Union two nodes a and b in the union-find structure"""
        self.add(a)
        self.add(b)

        root_a = self.find(a)
        root_b = self.find(b)

        if root_a == root_b:
            return

        if self.size[root_a] < self.size[root_b]:
            root_a, root_b = root_b, root_a

        self.parent[root_b] = root_a
        self.size[root_a] += self.size[root_b]

    def component_sizes(self) -> list[int]:
        """Return a list of sizes of all connected components in the union-find structure"""
        counts = {}

        for node in self.parent:
            root = self.find(node)
            counts[root] = counts.get(root, 0) + 1

        return list(counts.values())


def filter_edges(df: pd.DataFrame, filter_name: str) -> pd.DataFrame:
    """Return one support-based subset of the integrated network"""
    if filter_name == "all_edges":
        return df.copy()

    if filter_name == "consensus_2plus":
        return df[df["n_tools"] >= 2].copy()

    if filter_name == "consensus_3tools":
        return df[df["n_tools"] == 3].copy()

    raise ValueError(f"Unknown filter: {filter_name}")


def calculate_summary(
    edges: pd.DataFrame,
    threshold: str,
    network_filter: str,
    input_file: Path,
) -> dict:
    """Calculate basic network summary statistics for an integrated edge table"""
    n_edges = len(edges)

    if n_edges == 0:
        return {
            "collapse_rule": "best_bitscore",
            "threshold": threshold,
            "network_filter": network_filter,
            "input_file": str(input_file.relative_to(PROJECT_ROOT)),
            "nodes_with_at_least_one_edge": 0,
            "edges": 0,
            "average_degree": 0,
            "density": 0,
            "connected_components": 0,
            "largest_component_size": 0,
            "largest_component_fraction": 0,
        }

    self_edges = int((edges["source"] == edges["target"]).sum())
    duplicate_edges = int(edges.duplicated(subset=["source", "target"]).sum())

    all_nodes = pd.concat([edges["source"], edges["target"]], ignore_index=True)
    n_nodes = all_nodes.nunique()

    degree_series = all_nodes.value_counts()

    average_degree = (2 * n_edges / n_nodes) if n_nodes > 0 else 0
    density = (2 * n_edges / (n_nodes * (n_nodes - 1))) if n_nodes > 1 else 0

    uf = UnionFind()

    for source, target in zip(edges["source"], edges["target"]):
        uf.union(source, target)

    component_sizes = uf.component_sizes()
    connected_components = len(component_sizes)
    largest_component_size = max(component_sizes) if component_sizes else 0
    largest_component_fraction = (
        largest_component_size / n_nodes if n_nodes > 0 else 0
    )

    support_counts = edges["n_tools"].value_counts().to_dict()
    pattern_counts = edges["support_pattern"].value_counts().to_dict()

    return {
        "collapse_rule": "best_bitscore",
        "threshold": threshold,
        "network_filter": network_filter,
        "input_file": str(input_file.relative_to(PROJECT_ROOT)),
        "self_edges_detected": self_edges,
        "duplicate_edges_detected": duplicate_edges,
        "nodes_with_at_least_one_edge": n_nodes,
        "edges": n_edges,
        "average_degree": average_degree,
        "density": density,
        "connected_components": connected_components,
        "largest_component_size": largest_component_size,
        "largest_component_fraction": largest_component_fraction,
        "min_degree": degree_series.min(),
        "median_degree": degree_series.median(),
        "mean_degree": degree_series.mean(),
        "max_degree": degree_series.max(),
        "edges_supported_by_1_tool": support_counts.get(1, 0),
        "edges_supported_by_2_tools": support_counts.get(2, 0),
        "edges_supported_by_3_tools": support_counts.get(3, 0),
        "blastp_only": pattern_counts.get("blastp", 0),
        "mmseqs_only": pattern_counts.get("mmseqs", 0),
        "swipe_only": pattern_counts.get("swipe", 0),
        "blastp_mmseqs": pattern_counts.get("blastp_mmseqs", 0),
        "blastp_swipe": pattern_counts.get("blastp_swipe", 0),
        "mmseqs_swipe": pattern_counts.get("mmseqs_swipe", 0),
        "blastp_mmseqs_swipe": pattern_counts.get("blastp_mmseqs_swipe", 0),
        "median_pident_max": edges["pident_max"].median(),
        "median_align_len_max": edges["align_len_max"].median(),
        "median_bitscore_max": edges["bitscore_max"].median(),
        "min_evalue": edges["evalue_min"].min(),
        "max_evalue": edges["evalue_min"].max(),
    }


def process_threshold(threshold: str) -> list[dict]:
    """Process one integrated edge file for all support filters"""
    input_file = INTEGRATED_EDGE_ROOT / threshold / "integrated_edges.tsv"

    if not input_file.exists():
        print(f"Skipping missing file: {input_file}")
        return []

    print(f"\nReading integrated network: {threshold}")
    print(input_file)

    df = pd.read_csv(input_file, sep="\t", usecols=USECOLS)

    summary_rows = []

    for network_filter in ["all_edges", "consensus_2plus", "consensus_3tools"]:
        subset = filter_edges(df, network_filter)

        print(
            f"  {network_filter}: "
            f"{len(subset):,} edges"
        )

        summary_rows.append(
            calculate_summary(
                edges=subset,
                threshold=threshold,
                network_filter=network_filter,
                input_file=input_file,
            )
        )

    return summary_rows


def main() -> None:
    QC_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    all_rows = []

    for threshold in THRESHOLDS:
        all_rows.extend(process_threshold(threshold))

    summary_df = pd.DataFrame(all_rows)

    output_file = QC_OUTPUT_DIR / "integrated_network_summary_statistics.tsv"
    summary_df.to_csv(output_file, sep="\t", index=False)

    print("\nIntegrated network summary statistics:")
    print(summary_df.to_string(index=False))
    print(f"\nSummary written to: {output_file}")


if __name__ == "__main__":
    main()